### ISSUE TITLE
Portfolio managment

### ISSUE THREAD

**Issue by holymiko** [holymiko/ISA-server#25]
### Backend
- [ ] https://github.com/holymiko/ISA-server/issues/19
### Frontend
- [ ] https://github.com/holymiko/ISA-server/issues/14 
- [ ] https://github.com/holymiko/ISA-server/issues/16
