### ISSUE TITLE
Správa produktů

### ISSUE THREAD

**Issue by holymiko** [holymiko/ISA-server#26]
Možnost spravovat produkty v uživatelském rozhraní pro role ADMIN a SUPER_ADMIN 

### Front-end
- [x] Uložit nabídku jako samostatný produkt
- [x] Přiřadit nabídku k jinému produktu
- Doplnit nebo změnit informaci produktu (waiting)

### Back-end
- [x] Návrh DTO 
- [x] Endpoint a validace requestu
- [x] https://github.com/holymiko/ISA-server/issues/39
- [x] Impl. přepojení Linku na jiný produkt
- [x] Impl. napojení Linku na nový produkt
