### ISSUE TITLE
Správa uživatelů

### ISSUE THREAD

**Issue by holymiko** [holymiko/ISA-server#27]
### Role

GUEST - volně přístupný pohled do UI. Může nahlížet produkty a akcie
USER - přihlášený uživatel. Může zakládat portfolia a přidávat investice. Vidí svoje portfolia
ADMIN - vidí všechny klienty, má přístup na tabulku user managmentu, (readonly) vidí všechny portfolia, může spravovat produkty 
SUPER_ADMIN - vše jako ADMIN + v tabulce user managmentu vidí i ADMIN users. Může měnit portfolia

Další případně: DEALER, CLIENT

### Funkcionality
vytvořit uživatele
přidat uživateli username a password
odstranit uživatele
změnit heslo 
vygenerovat heslo
 
přiřadit uživateli portfolia
odstranit uživatele včetně portfolií

### Frontend
-  změnit heslo (waiting) 
-  vygenerovat heslo (waiting)
- [x] https://github.com/holymiko/ISA-server/issues/11
- [x] https://github.com/holymiko/ISA-server/issues/34
- [x] https://github.com/holymiko/ISA-server/issues/35

### Backend
- [x] https://github.com/holymiko/ISA-server/issues/10
