### ISSUE TITLE
Sreality modul

### ISSUE THREAD

**Issue by holymiko** [holymiko/ISA-server#7]
Implementace celého modulu

### BE
- [ ] Vytvoř datový model
- [ ] Vyber zdrojové servery
- [ ] Implementuj scraping
- [ ] Implementuj endpoint a DTO

### FE
- [ ] Implementuj RealityListPage
- [ ] Implementuj RealityPage
- [ ] doc - napiš rešerši 

Možný zdroj:
> https://www.sreality.cz/api/cs/v1/estates
> odkaz na diplomku z FITu https://dspace.cvut.cz/bitstream/handle/10467/65129/F8-DP-2016-Dorda-Marek-thesis.pdf?sequence=-1&isAllowed=y
